[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
markers =
    authentication: тесты аутентификации
    access_control: тесты контроля доступа
    student: тесты для студентов
    teacher: тесты для преподавателей
